name: build java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - java/**
permissions:
  packages: write

jobs:
  build:
    name: "build:java_${{ matrix.tag }} (${{ matrix.config.platform }})"
    runs-on: ${{ matrix.config.runner }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - platform: linux/amd64
            platform_suffix: amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            platform_suffix: arm64
            runner: ubuntu-24.04-arm
        tag:
          - 8
          - 11
          - 16
          - 17
          - 19
          - 21
          - 22
          - 25
          - 26
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v4
        with:
          buildkitd-flags: --debug
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v7
        with:
          context: ./java
          file: ./java/${{ matrix.tag }}/Dockerfile
          platforms: ${{ matrix.config.platform }}
          push: true
          tags: |
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-${{ matrix.config.platform_suffix }}
            ${{ github.repository_owner == 'pelican-eggs' && format('ghcr.io/parkervcp/yolks:java_{0}-{1}', matrix.tag, matrix.config.platform_suffix) || '' }}
      - name: Retry build
        if: failure()
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          command: |
            docker buildx build \
              --file ./java/${{ matrix.tag }}/Dockerfile \
              --platform ${{ matrix.config.platform }} \
              --push \
              --tag ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-${{ matrix.config.platform_suffix }} \
              ./java

  merge:
    name: "merge:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 16
          - 17
          - 19
          - 21
          - 22
          - 25
          - 26
    steps:
      - id: lower-repo
        name: Repository to lowercase
        run: |
          echo "repository=${GITHUB_REPOSITORY_OWNER@L}" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ steps.lower-repo.outputs.repository }}
          password: ${{ secrets.REGISTRY_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Create multi-arch manifest
        run: |
          docker buildx imagetools create -t ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }} \
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-amd64 \
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-arm64
      - name: Create pelican-eggs tag
        if: github.repository_owner == 'pelican-eggs'
        run: |
          docker buildx imagetools create -t ghcr.io/parkervcp/yolks:java_${{ matrix.tag }} \
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-amd64 \
            ghcr.io/${{ steps.lower-repo.outputs.repository }}/yolks:java_${{ matrix.tag }}-arm64
